[package]
name = "pdf-postprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.12"
log = "0.4.22"
lopdf = "0.33.0"
tracing-subscriber = { version = "0.3.18", features=["env-filter"]}
walkdir = "2.5.0"
